#!/usr/bin/env tsx
/**
 * Scans src/lib/lessons/{subject}/{topic}/{chapter}.ts and generates
 * src/lib/lessons/data.generated.ts — a typed registry of every chapter.
 *
 * Re-run: pnpm build:registry  (also runs in predev / prebuild).
 * The output is committed.
 */
import { readdir, stat, writeFile } from "node:fs/promises";
import path from "node:path";

export async function buildRegistry(lessonsDir: string, outPath: string): Promise<void> {
  const entries: Array<{
    subject: string;
    topicSlug: string;
    chapterSlug: string;
    importPath: string;
    identifier: string;
  }> = [];
  const subjects = await readdir(lessonsDir);

  for (const subject of subjects) {
    const subjectDir = path.join(lessonsDir, subject);
    const subjectStat = await stat(subjectDir).catch(() => null);
    if (!subjectStat?.isDirectory()) continue;

    const topics = await readdir(subjectDir);
    for (const topicSlug of topics) {
      const topicDir = path.join(subjectDir, topicSlug);
      const topicStat = await stat(topicDir).catch(() => null);
      if (!topicStat?.isDirectory()) continue;

      const files = await readdir(topicDir);
      for (const file of files) {
        if (!file.endsWith(".ts") || file.endsWith(".test.ts") || file.endsWith(".d.ts")) continue;
        const chapterSlug = file.slice(0, -3);
        const importPath = `./${subject}/${topicSlug}/${chapterSlug}`;
        const identifier = `${subject}__${topicSlug.replace(/-/g, "_")}__${chapterSlug.replace(/-/g, "_")}`;
        entries.push({ subject, topicSlug, chapterSlug, importPath, identifier });
      }
    }
  }

  entries.sort((a, b) => a.importPath.localeCompare(b.importPath));

  const importLines = entries.map(
    (e) => `import { chapter as ${e.identifier} } from "${e.importPath}";`
  );
  const recordLines = entries.map(
    (e) => `  "${e.topicSlug}/${e.chapterSlug}": ${e.identifier},`
  );

  const content = `// AUTO-GENERATED by scripts/build-registry.ts — do not edit.
// Regenerate with: pnpm build:registry
import type { ChapterDefinition } from "@/types/chapter";

${importLines.join("\n")}

export const chapters: Readonly<Record<string, ChapterDefinition>> = {
${recordLines.join("\n")}
};
`;

  await writeFile(outPath, content, "utf8");
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const lessonsDir = path.resolve("src/lib/lessons");
  const outPath = path.join(lessonsDir, "data.generated.ts");
  buildRegistry(lessonsDir, outPath).then(() => {
    console.log(`Wrote ${outPath}`);
  }).catch((e) => {
    console.error(e);
    process.exit(1);
  });
}
