// AUTO-GENERATED by scripts/build-registry.ts — do not edit.
// Regenerate with: pnpm build:registry
import type { ChapterDefinition } from "@/types/chapter";

import { chapter as math__absolute_value__intro } from "./math/absolute-value/intro";
import { chapter as math__algebraic_expressions__intro } from "./math/algebraic-expressions/intro";
import { chapter as math__analytic_geometry__intro } from "./math/analytic-geometry/intro";
import { chapter as math__circles__intro } from "./math/circles/intro";
import { chapter as math__combinatorics__intro } from "./math/combinatorics/intro";
import { chapter as math__derivatives__applications } from "./math/derivatives/applications";
import { chapter as math__derivatives__intro } from "./math/derivatives/intro";
import { chapter as math__exponential_functions__intro } from "./math/exponential-functions/intro";
import { chapter as math__inequalities__intro } from "./math/inequalities/intro";
import { chapter as math__integrals__intro } from "./math/integrals/intro";
import { chapter as math__limits__intro } from "./math/limits/intro";
import { chapter as math__linear_equations__intro } from "./math/linear-equations/intro";
import { chapter as math__linear_equations__word_problems } from "./math/linear-equations/word-problems";
import { chapter as math__linear_functions__intro } from "./math/linear-functions/intro";
import { chapter as math__logarithmic_functions__intro } from "./math/logarithmic-functions/intro";
import { chapter as math__probability__intro } from "./math/probability/intro";
import { chapter as math__quadratic_equations__intro } from "./math/quadratic-equations/intro";
import { chapter as math__quadratic_functions__intro } from "./math/quadratic-functions/intro";
import { chapter as math__sequences__intro } from "./math/sequences/intro";
import { chapter as math__solid_geometry__intro } from "./math/solid-geometry/intro";
import { chapter as math__systems_of_equations__intro } from "./math/systems-of-equations/intro";
import { chapter as math__triangles__intro } from "./math/triangles/intro";
import { chapter as math__trigonometric_functions__intro } from "./math/trigonometric-functions/intro";
import { chapter as physics__dynamics__intro } from "./physics/dynamics/intro";
import { chapter as physics__electric_circuits__intro } from "./physics/electric-circuits/intro";
import { chapter as physics__electric_field__intro } from "./physics/electric-field/intro";
import { chapter as physics__energy_and_work__intro } from "./physics/energy-and-work/intro";
import { chapter as physics__gravity__intro } from "./physics/gravity/intro";
import { chapter as physics__ideal_gas__intro } from "./physics/ideal-gas/intro";
import { chapter as physics__kinematics__intro } from "./physics/kinematics/intro";
import { chapter as physics__kinematics__projectile_motion } from "./physics/kinematics/projectile-motion";
import { chapter as physics__magnetic_field__intro } from "./physics/magnetic-field/intro";
import { chapter as physics__mechanical_waves__intro } from "./physics/mechanical-waves/intro";
import { chapter as physics__momentum_and_impulse__intro } from "./physics/momentum-and-impulse/intro";
import { chapter as physics__optics__intro } from "./physics/optics/intro";
import { chapter as physics__quantum_physics__intro } from "./physics/quantum-physics/intro";
import { chapter as physics__temperature_and_heat__intro } from "./physics/temperature-and-heat/intro";
import { chapter as physics__thermodynamics_laws__intro } from "./physics/thermodynamics-laws/intro";

export const chapters: Readonly<Record<string, ChapterDefinition>> = {
  "absolute-value/intro": math__absolute_value__intro,
  "algebraic-expressions/intro": math__algebraic_expressions__intro,
  "analytic-geometry/intro": math__analytic_geometry__intro,
  "circles/intro": math__circles__intro,
  "combinatorics/intro": math__combinatorics__intro,
  "derivatives/applications": math__derivatives__applications,
  "derivatives/intro": math__derivatives__intro,
  "exponential-functions/intro": math__exponential_functions__intro,
  "inequalities/intro": math__inequalities__intro,
  "integrals/intro": math__integrals__intro,
  "limits/intro": math__limits__intro,
  "linear-equations/intro": math__linear_equations__intro,
  "linear-equations/word-problems": math__linear_equations__word_problems,
  "linear-functions/intro": math__linear_functions__intro,
  "logarithmic-functions/intro": math__logarithmic_functions__intro,
  "probability/intro": math__probability__intro,
  "quadratic-equations/intro": math__quadratic_equations__intro,
  "quadratic-functions/intro": math__quadratic_functions__intro,
  "sequences/intro": math__sequences__intro,
  "solid-geometry/intro": math__solid_geometry__intro,
  "systems-of-equations/intro": math__systems_of_equations__intro,
  "triangles/intro": math__triangles__intro,
  "trigonometric-functions/intro": math__trigonometric_functions__intro,
  "dynamics/intro": physics__dynamics__intro,
  "electric-circuits/intro": physics__electric_circuits__intro,
  "electric-field/intro": physics__electric_field__intro,
  "energy-and-work/intro": physics__energy_and_work__intro,
  "gravity/intro": physics__gravity__intro,
  "ideal-gas/intro": physics__ideal_gas__intro,
  "kinematics/intro": physics__kinematics__intro,
  "kinematics/projectile-motion": physics__kinematics__projectile_motion,
  "magnetic-field/intro": physics__magnetic_field__intro,
  "mechanical-waves/intro": physics__mechanical_waves__intro,
  "momentum-and-impulse/intro": physics__momentum_and_impulse__intro,
  "optics/intro": physics__optics__intro,
  "quantum-physics/intro": physics__quantum_physics__intro,
  "temperature-and-heat/intro": physics__temperature_and_heat__intro,
  "thermodynamics-laws/intro": physics__thermodynamics_laws__intro,
};
